"""Pack the battle terrain into web/terrain.js.

Reads the Unity TerrainData (Rehaf-assets/OldAssetsJustIncase/New Terrain.asset, used by
Level.prefab in every battle scene) with UnityPy, crops the heightmap and the painted
road splat map around each battle, and embeds the two splat textures (grass, road).
The scenes tile the same TerrainData twice: level1terrain at z = -212.6 and
Terrain (2) at z = 286, both at x = -547.6, each 500 x 500 units.

    python3 -m pip install UnityPy numpy pillow
    python3 web/tools/build-terrain.py
"""
import base64, io, json, os
import numpy as np
import UnityPy
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, '..', '..', 'Assets')
TERRAIN = os.path.join(ASSETS, 'Rehaf-assets/OldAssetsJustIncase/New Terrain.asset')
TEXTURES = {'grass': 'Rehaf-assets/Art/grasstexture.png', 'road': 'Rehaf-assets/Art/road.png'}
X0, SIZE = -547.6, 500.0
TILES_Z = (-212.6, 286.0)
# Unity-space rectangles around each battle (x0, x1, z0, z1)
REGIONS = {'level2': (-372, -188, 150, 296), 'level4': (-420, -146, 522, 642)}

env = UnityPy.load(TERRAIN)
heights = alpha = None
for obj in env.objects:
    if obj.type.name == 'TerrainData':
        hm = obj.read_typetree()['m_Heightmap']
        n = hm['m_Width']
        heights = np.array(hm['m_Heights'], dtype=np.float32).reshape(n, n) / 32766.0 * hm['m_Scale']['y']  # [z][x]
    elif obj.type.name == 'Texture2D':
        alpha = np.array(obj.read().image)[::-1, :, 1]  # green channel = road layer, rows from low z

def sample(arr, x, z):
    oz = TILES_Z[0] if z < TILES_Z[1] + 1.4 else TILES_Z[1]
    res = arr.shape[0] - (1 if arr is heights else 0)
    i = int(round((x - X0) / SIZE * res)); j = int(round((z - oz) / SIZE * res))
    return arr[min(max(j, 0), arr.shape[0] - 1), min(max(i, 0), arr.shape[1] - 1)]

STEP = SIZE / 512
out = {'step': STEP, 'regions': {}}
for name, (x0, x1, z0, z1) in REGIONS.items():
    nx, nz = int((x1 - x0) / STEP) + 1, int((z1 - z0) / STEP) + 1
    h = np.zeros((nz, nx), np.uint16); m = np.zeros((nz, nx), np.uint8)
    for j in range(nz):
        for i in range(nx):
            x, z = x0 + i * STEP, z0 + j * STEP
            h[j, i] = int(round(sample(heights, x, z) * 100)); m[j, i] = sample(alpha, x, z)
    out['regions'][name] = {'x0': x0, 'z0': z0, 'nx': nx, 'nz': nz,
                            'h': base64.b64encode(h.astype('<u2').tobytes()).decode(), 'm': base64.b64encode(m.tobytes()).decode()}
    print(name, nx, nz, 'max height', h.max() / 100)
for key, rel in TEXTURES.items():
    buf = io.BytesIO(); Image.open(os.path.join(ASSETS, rel)).convert('RGB').save(buf, 'JPEG', quality=86)
    out[key] = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
with open(os.path.join(HERE, '..', 'terrain.js'), 'w') as f:
    f.write('// Generated by tools/build-terrain.py from the Unity terrain. Heights in cm, road mask 0-255.\n')
    f.write('window.CATDOG_TERRAIN = ' + json.dumps(out) + ';\n')
