#!/usr/bin/env python3
"""Pack the original CatDog 2D art into web/art.js (base64 WebP/JPEG).

Also writes downscaled model textures to tools/tex/ for export-models.html.
Run from the repo root:  python3 web/tools/build-art.py
Needs Pillow (python3 -m pip install pillow).
"""
import base64, io, json, os
from PIL import Image

A = 'Assets/'
ART = {
    # Cat parents (King of the South = grey cat, Queen of the North = black cat)
    'catKing_happy':  'Rehaf-assets/Art/2d_part/catoneexpressions1.png',
    'catKing_angry':  'Rehaf-assets/Art/2d_part/catoneexpressions2.png',
    'catKing_smug':   'Rehaf-assets/Art/2d_part/catoneexpressions3.png',
    'catQueen_snark': 'Rehaf-assets/Art/2d_part/cat_female_exp_0007_Layer-8-copy-2.png',
    'catQueen_angry': 'Rehaf-assets/Art/2d_part/cat_female_exp_0008_Layer-8-copy-3.png',
    'catQueen_happy': 'Rehaf-assets/Art/2d_part/cat_female_exp_0009_Layer-8-copy-6.png',
    # Dog parents
    'dogKing_happy':  '1Che Dialogue Scenes/art_new/happyDogDad.png',
    'dogKing_angry':  '1Che Dialogue Scenes/art_new/angryDogDad.png',
    'dogKing_smug':   '1Che Dialogue Scenes/art_new/normalDogdad.png',
    'dogQueen_snark': '1Che Dialogue Scenes/art_new/SnarkyDogMom.png',
    'dogQueen_angry': '1Che Dialogue Scenes/art_new/AngryDogmom.png',
    'dogQueen_happy': '1Che Dialogue Scenes/art_new/HappyDogMom.png',
}
BG = {
    'catHall': 'Rehaf-assets/Art/2d_part/background1.png',
    'dogHall': '1Che Dialogue Scenes/art_new/24825952_311242952723993_1671727932_o.png',
}
BANNER = {
    'catBanner': 'Rehaf-assets/Art/2d_part/longCatBanner.png',
    'dogBanner': '1Che Dialogue Scenes/art_new/longdogbanner.png',
}
TEX = {
    'catmage': 'Rehaf-assets/Textures/catmage1/CatMageFBX_Material_AlbedoTransparency.png',
    'dogmage': 'Rehaf-assets/Textures/dogWizzardTexture1/DogMagev5_Material_AlbedoTransparency.png',
    'fleablue': 'Rehaf-assets/Textures/BlueFlea1/Flea_Material_AlbedoTransparency.png',
    'fleared': 'Rehaf-assets/Textures/redFlea2/Flea_Material_AlbedoTransparency.png',
    'cart': 'Rehaf-assets/Textures/CatCartTexture/cannon_Material.001_AlbedoTransparency.png',
    'catcastle': 'Rehaf-assets/Textures/catCastle1/catCastle_Material_AlbedoTransparency.png',
    'bone': 'Rehaf-assets/Textures/BoneTextures2/boneTower_Material_AlbedoTransparency.png',
    'boneflag': 'Rehaf-assets/Textures/BoneTextures2/boneTower_Flag_AlbedoTransparency.png',
    'banner': 'Rehaf-assets/Art/banner.png',
    'tree': 'Rehaf-assets/Textures/Treetexture/Tree_Material_AlbedoTransparency.png',
    'treeleaf': 'Rehaf-assets/Textures/Treetexture/Tree_TREE_AlbedoTransparency.png',
    'rocks': 'Rehaf-assets/Textures/rocks/rocks1_Material_AlbedoTransparency.png',
    'coin': 'Rehaf-assets/Textures/coin/coin_coin_AlbedoTransparency.png',
}

def uri(im, fmt, **kw):
    b = io.BytesIO(); im.save(b, fmt, **kw)
    return 'data:image/%s;base64,%s' % (fmt.lower(), base64.b64encode(b.getvalue()).decode())

out = {}
for k, p in ART.items():
    im = Image.open(A + p).convert('RGBA'); im = im.crop(im.getbbox()); im.thumbnail((620, 620))
    out[k] = uri(im, 'WEBP', quality=80)
CROP = {'catHall': (0, 250, 1800, 1885)}  # trim the flat blue margins baked into background1.png
for k, p in BG.items():
    im = Image.open(A + p).convert('RGB')
    if k in CROP: im = im.crop(CROP[k])
    im.thumbnail((1100, 1100))
    out[k] = uri(im, 'JPEG', quality=72)
for k, p in BANNER.items():
    im = Image.open(A + p).convert('RGBA'); im = im.crop(im.getbbox()); im.thumbnail((260, 460))
    out[k] = uri(im, 'WEBP', quality=80)

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, '..', 'art.js'), 'w') as f:
    f.write('// Generated by tools/build-art.py from the original CatDog art. Do not edit.\n')
    f.write('window.CATDOG_ART = ' + json.dumps(out, indent=0) + ';\n')

os.makedirs(os.path.join(here, 'tex'), exist_ok=True)
for k, p in TEX.items():
    im = Image.open(A + p).convert('RGB'); im.thumbnail((512, 512))
    im.save(os.path.join(here, 'tex', k + '.jpg'), quality=82)
print('art.js', os.path.getsize(os.path.join(here, '..', 'art.js')) // 1024, 'KB')
