// Converts the original FBX models into web/models.js (base64 GLB).
// Usage (from web/tools):  npm i three@0.160.0 playwright  &&  node export-models.mjs
// Needs tools/tex/ from build-art.py. Serves the repo root on :8765 while it runs.
import {chromium} from 'playwright';
import fs from 'fs'; import http from 'http'; import path from 'path'; import {fileURLToPath} from 'url';
const here = path.dirname(fileURLToPath(import.meta.url)); const root = path.resolve(here, '../..');
// three r160's FBXLoader throws on the empty rotation tracks in these files; skip them instead.
const src = fs.readFileSync(path.join(here, 'node_modules/three/examples/jsm/loaders/FBXLoader.js'), 'utf8')
  .replace("if ( ! values || ! times ) return new QuaternionKeyframeTrack( modelName + '.quaternion', [], [] );", "if ( ! values || ! times || times.length === 0 ) return undefined;")
  .replace("'../curves/NURBSCurve.js'", "'three/addons/curves/NURBSCurve.js'").replace("'../libs/fflate.module.js'", "'three/addons/libs/fflate.module.js'");
fs.writeFileSync(path.join(here, 'FBXLoaderPatched.js'), src);
const types = {'.html': 'text/html', '.js': 'text/javascript', '.jpg': 'image/jpeg', '.fbx': 'application/octet-stream'};
const srv = http.createServer((q, r) => { const f = path.join(root, decodeURIComponent(q.url.split('?')[0]));
  fs.readFile(f, (e, d) => { if (e) { console.log('404', q.url); r.writeHead(404); r.end(); } else { r.writeHead(200, {'Content-Type': types[path.extname(f)] || 'application/octet-stream'}); r.end(d); } }); }).listen(8765);
const b = await chromium.launch(process.env.CHROMIUM ? {executablePath: process.env.CHROMIUM} : {});
const p = await b.newPage(); p.on('console', m => { if (!/skinning|decay/.test(m.text())) console.log(m.text()); });
await p.goto('http://localhost:8765/web/tools/export-models.html');
await p.waitForFunction(() => window.RESULT, null, {timeout: 300000});
const r = await p.evaluate(() => window.RESULT);
fs.writeFileSync(path.join(root, 'web/models.js'), '// Generated by tools/export-models.mjs from Assets/Rehaf-assets/models/*.fbx. Do not edit.\nwindow.CATDOG_MODELS = ' + JSON.stringify(r, null, 0).replace(/","/g, '",\n"') + ';\n');
fs.unlinkSync(path.join(here, 'FBXLoaderPatched.js'));
await b.close(); srv.close();
