// CatDog story script.
// Every line below comes from the original Fungus flowcharts in
// "Assets/1Che Dialogue Scenes" (CLevel1/3/5 and DLevel1/3/5), with spelling fixed.
// Only the three INTRO lines are new (the original intro scene, Level0, was placeholder text).
//
// Line format: [who, mood, text]   who: Q Queen of the North (Mom), K King of the South (Dad),
//                                        S Sister, B Brother, Y You, N narrator
//              mood: happy | angry | smug (King) / happy | angry | snark (Queen), or '' to keep the last one
//              {w} is Fungus's "wait" tag: a short pause while the line types out.
// {choice:[...]}  each option: t = label, d = +1 sides with Mom / -1 sides with Dad, go = next scene
// {tally:n}       Fungus "Decision tally": score > 0 means Mom helps, otherwise Dad helps
// {go:key} / {finish:true}
window.CATDOG_STORY = {
  chapters: [
    { title: 'Thanksgiving', start: 'c1_thanks' },
    { title: 'The Cocktail Party', start: 'c2_party' },
    { title: 'The Inheritance', start: 'c3_inherit' },
  ],
  intro: [
    ['N', '', 'The Cat Kingdom and the Dog Kingdom are at war. Again.'],
    ['N', '', 'You were crowned king last week. Your first war starts now.'],
    ['N', '', 'Your parents, the Queen of the North and the King of the South, are divorced. Both of them want to help you win. Both of them want you on their side.'],
  ],
  ending: [
    ['Q', 'happy', 'Looks like you won your war.'],
    ['K', 'happy', 'Really? Our son won a war?'],
    ['Q', '', 'Yup.'],
    ['K', '', 'My offensive upgrades must have really helped. Yup. I nailed it.'],
    ['Q', 'snark', '… {w}Your offenses helped your son win the war about as much as all that whiskey helped you win in our bedroom.'],
    ['K', '', 'So you’re saying I helped win the war...'],
    ['Q', '', 'In THAT case I’m saying that your offenses almost made him lose the war,'],
    ['Q', '', 'right before he claims he’s never lost a war like that before and then falls asleep snoring in my ear.'],
    ['K', '', 'So you’re saying I helped win the war...'],
    ['Q', '', 'I hate you so much right now.'],
    ['K', 'angry', 'I hate you too.'],
    ['Q', '', 'I’m glad I cheated on you.'],
    ['K', '', 'I’m glad you’re going to die alone.'],
    ['Q', '', 'We women tend to live longer than our men. So I can’t wait to drink a bunch of champagne and nap on your grave,'],
    ['Q', '', 'so I can wet the bed one last time.'],
    ['K', 'smug', 'I can’t wait for you to read my last will and testament so you can find out that I left everything to my other family you don’t know about.'],
    ['Q', 'happy', '...but he won the war.'],
    ['K', 'happy', 'Yeah, he won the war... We did a good job raising him, didn’t we?'],
    ['Q', '', 'Yes. We did at least do one good thing together.'],
    ['K', '', 'You know, it wasn’t so bad now that I’m looking back on it. I still miss you. {w}'],
    ['Q', '', 'Maybe… {w}MAYBE {w}I miss you too.'],
    ['K', '', 'I think we’re supposed to be together. So how about it? Wanna try again?'],
    ['Q', '', 'Really?'],
    ['K', '', 'Really.'],
    ['Q', '', '… {w}… {w}… {w}NOPE.'],
    { finish: true },
  ],
  scenes: {
    // ---------- Chapter 1 (CLevel1 / DLevel1) ----------
    c1_thanks: [
      ['Q', 'happy', 'Hello son. How’s the war going?'],
      ['Y', '', 'It’s go-'],
      ['Q', 'angry', 'Well that’s great to hear. I trust you’ll be coming over for Thanksgiving.'],
      ['Q', '', 'I’d hate for you to go a year without your mother’s famous Thanksgiving turkey.'],
      ['K', 'happy', 'You’re a grown man now, boy. No need to pretend to enjoy your mother’s burnt bird every year.'],
      ['K', '', 'Come hang with your pops and we’ll have a REAL celebration.'],
      ['Q', 'snark', 'Oh look what the poor side of the family dragged in. {w}Itself.'],
      ['K', 'happy', 'Aww. Missed you too.'],
      ['Q', '', 'You can’t say my turkey was bad after you ate it for 17 years.'],
      ['K', 'happy', 'I held my nose for every one of them.'],
      ['Q', '', 'You’d probably eat anything.'],
      ['K', 'smug', 'Clearly.'],
      ['Q', '', '...'],
      ['Q', 'happy', 'Anyway. My baby boy isn’t going to spend his Thanksgiving getting drunk at a bar'],
      ['Q', '', 'and watching you chase your own tail like you did every year of our marriage.'],
      ['K', 'happy', 'Who told you it was MY tail I was chasing at the bar all those years?'],
      ['Q', '', '... {w}(Don’t let him get to you. Just like the therapist said... {w}breathe in...)'],
      ['K', 'happy', 'The boy is grown now. He can make his own decisions. I’m sure he’ll want to spend Thanksgiving with his pops.'],
      ['Q', 'happy', 'And I’m sure he’ll choose to spend the holiday with the woman who gave birth to him. {w}Don’t you?'],
      { choice: [
        { t: 'Spend Thanksgiving with Mom', d: 1, go: 'c1_momThanks' },
        { t: 'Spend Thanksgiving with Dad', d: -1, go: 'c1_dadThanks' },
      ] },
    ],
    c1_momThanks: [
      ['Q', 'happy', 'Good boy. Love thy mother.'],
      ['K', 'angry', 'Whatever. {w}More for me...'],
      { go: 'c1_tell' },
    ],
    c1_dadThanks: [
      ['K', 'happy', 'Haha, my boy. We’re going to have one hell of a party.'],
      ['Q', 'snark', 'I see a mother’s love is quickly forgotten. {w}Good thing my other children still love me.'],
      { go: 'c1_tell' },
    ],
    c1_tell: [
      ['K', 'smug', 'Will you please tell your mother that I wasn’t there for your early birthdays'],
      ['K', '', 'because I was busy winning the war to protect our kingdom.'],
      ['Q', 'angry', 'Will you please remind your father that we know he started that war just to get out of the house.'],
      ['K', '', 'Do you see how she treats me? {w}You’d think I cheated on her or something.'],
      ['Q', '', 'You DID cheat on me. {w}Or something.'],
      ['K', 'angry', 'I never said I didn’t. {w}But now that you THINK I did....'],
      ['K', 'happy', 'I. {w}AM. {w}Offended.'],
      ['Q', '', '...'],
      ['Q', '', 'Please tell your father that when you grow up, you’ll stick around and be there to watch your children come of age.'],
      ['K', 'smug', 'Please tell your mother that you’ve learned from my mistakes {w}and hence won’t be getting married in the first place.'],
      ['Q', '', 'Please tell your father that he drank so much that having him home was just like having him not home.'],
      ['Q', '', 'Just with less puke...'],
      ['K', 'happy', 'I only threw up because I ate her cooking... {w}Please tell your mother that one, hehe.'],
      ['Q', '', 'Please tell your father that our marriage didn’t last {w}because he never really wanted it to.'],
      ['K', 'smug', 'Please tell your mother that she should have never mentioned getting a divorce if she didn’t REALLY want one.'],
      { choice: [
        { t: 'Tell your mother what your father said', d: -1, go: 'c1_momFault' },
        { t: 'Tell your father what your mother said', d: 1, go: 'c1_dadFault' },
      ] },
    ],
    c1_momFault: [
      ['Q', 'angry', 'So you’re taking your father’s side on this… {w}Duly noted.'],
      ['K', 'happy', 'You’ve got your father’s better judgement. It’ll do you well.'],
      { go: 'c1_sibs' },
    ],
    c1_dadFault: [
      ['Q', 'angry', 'Haha, I told you it was all your fault. {w}ALL. {w}YOUR. {w}FAULT!!!'],
      ['K', 'angry', 'You don’t have to take the woman’s side on everything. {w}Whatever, {w}I’m out of here.'],
      { go: 'c1_sibs' },
    ],
    c1_sibs: [
      ['S', '', 'Big sister here, and guess what?'],
      ['Y', '', '... {w}'],
      ['S', '', 'I have a surprise for you!'],
      ['Y', '', '... {w}'],
      ['S', '', 'Me and the husband have to leave town for the weekend. You get to finally'],
      ['S', '', 'spend some time with your new niece while you babysit her.'],
      ['S', '', '...Aren’t you excited?'],
      ['B', '', 'Hold up, lil bro. You might not wanna commit to that 2-year-old’s tea party just yet.'],
      ['B', '', 'I have front row tickets to the gladiator stadium on the same weekend. {w}No kids allowed.'],
      ['S', '', 'You haven’t met your niece yet. {w}This is a perfect opportunity for you to spend some time with her.'],
      ['B', '', 'BOOO. {w}Babies are boring. Wait till she’s about ten to babysit her.'],
      ['B', '', 'Then you can teach her all the cool curse words. She won’t even remember it now. It’s kind of a waste.'],
      ['S', '', 'You wouldn’t really choose to spend your weekend watching savage men kill each other {w}'],
      ['S', '', 'rather than take a proper step into your role as an uncle. Would you?'],
      { choice: [
        { t: 'Babysit your niece', d: 1, go: 'c1_babysit' },
        { t: 'Go to the gladiator games', d: -1, go: 'c1_glad' },
      ] },
    ],
    c1_babysit: [
      ['S', '', 'Oh, thanks so much. You’re the best.'],
      ['Q', 'happy', 'Awww.... {w}Look at the new uncle!'],
      { go: 'c1_gf' },
    ],
    c1_glad: [
      ['B', '', 'We’re gonna have a blast. There’s gonna be SOOO many decapitations!!!'],
      ['S', '', 'Okay then. {w}Have fun, I guess.'],
      ['K', 'happy', 'You mind if I join my boys at the great games? {w}Awesome!'],
      ['Q', 'snark', 'You really should have helped your sister and spent some time with your niece. {w}These years are precious.'],
      { go: 'c1_gf' },
    ],
    c1_gf: [
      ['Q', 'happy', 'Hey son. Don’t you find it somewhat peculiar that your father found another girlfriend so soon after our divorce?'],
      ['K', 'smug', 'I’m right here. You can ask ME, because I’m LITERALLY right here.'],
      ['Q', '', 'Nothing against... what’s her name?'],
      ['K', '', 'Ashley.'],
      ['Q', '', 'Yes, Trashley. Nothing against poor Trashley, but did you even have time to flip the mattress before she slithered into my dirty catnip?'],
      ['K', 'angry', 'Son, don’t you think it’s normal for a single man to find someone that makes him happy? {w}For the first time ever.'],
      ['K', '', 'In fact, don’t you think it’s weird that your mother isn’t dating?'],
      ['Q', '', 'Right here, guys. Literally right here in front of you. And {w}I’m waiting for the right time.'],
      ['K', '', 'The right time for what?'],
      ['Q', '', 'Can’t a woman have a little dignity about her love life in her later years?'],
      ['K', '', 'Is that what you call over-mothering your grown children because you’re afraid nobody else wants you?'],
      ['K', '', 'It’s perfectly normal for me to have a new woman in my life.'],
      ['Q', '', 'Well, I still think it’s a little sketchy to have one so soon. Don’t you agree, son?'],
      { choice: [
        { t: 'Nothing wrong with finding love', d: -1, go: 'c1_love' },
        { t: 'It seems a bit soon', d: 1, go: 'c1_soon' },
      ] },
    ],
    c1_love: [
      ['K', 'happy', 'Told ya!'],
      ['Q', 'snark', 'Well, I see how the love in this room works. Just don’t bring your new mom to my funeral the day after I get hit by a truck.'],
      { tally: 1 },
    ],
    c1_soon: [
      ['Q', 'happy', 'Couldn’t have said it better myself. Certainly makes you wonder about the REAL cause of our marriage failing!'],
      ['K', 'angry', 'GENDER TRAITOR!!!'],
      { tally: 1 },
    ],
    t1_mom: [
      ['K', 'smug', 'You’ve been acting too much like your mother for my taste.'],
      ['K', 'angry', 'Good luck winning your first war. You’re on your own now. Just like I was.'],
      ['Q', 'snark', 'Ignore your father. He lost every war he fought anyway.'],
      ['Q', '', 'I’ll bolster your minions and defenses.'],
      { go: 'c1_end' },
    ],
    t1_dad: [
      ['Q', 'angry', 'You wanna be just like your father? {w}Then fight alone, just like your father.'],
      ['K', 'happy', 'That’s my boy. Don’t listen to her.'],
      ['K', '', 'I’ll be around to upgrade your troops, and make them the fiercest warriors there ever were.'],
      { go: 'c1_end' },
    ],
    c1_end: [
      ['K', 'smug', 'Was I really so bad?'],
      ['Q', 'happy', 'It depends. Did you really see other women?'],
      ['K', '', 'Well, I am a king after all.'],
      ['Q', '', 'But still a husband.'],
      ['K', '', 'You spent a lot of time locked in your quarters with your servants. {w}I never asked any questions.'],
      ['Q', '', 'It’s not cheating if you use the help.'],
      ['K', 'angry', 'Must be a new rule.'],
      { finish: true },
    ],

    // ---------- Chapter 2 (CLevel3 / DLevel3) ----------
    c2_party: [
      ['K', 'happy', 'How’s the war going?'],
      ['Y', '', '...'],
      ['K', 'smug', 'That bad, huh?'],
      ['Q', 'happy', 'Hello son. I trust all is well.'],
      ['Q', '', 'I hope you can take next Wednesday off from the war. I’m hosting a dinner for the neighborhood alley association.'],
      ['Q', '', 'I’d like you to help your mother with serving drinks.'],
      ['K', 'angry', 'NOPE! Not my son.'],
      ['Q', 'snark', 'Excuse me?'],
      ['K', '', 'I pay your mother WAY too much in alimony for her to be asking you for help. {w}She can take some of that money I give her and hire extra hands.'],
      ['Q', '', 'Don’t ask him to treat his own mother like you treated our marriage. {w}He can’t just hire help instead of taking care of his responsibilities at home.'],
      ['K', 'smug', 'Don’t remind me. I spent a ton of money on that riding coach to teach you about horses.'],
      ['Q', '', 'And he did a great job teaching me how to ride. {w}But what’s a horse?'],
      ['K', 'angry', 'Grrrrhhhhh (breathe in... {w}breathe out.... {w}hate thine ex, love thine self... breathe)'],
      ['Q', '', 'I tease, I tease. {w}I would NEVER tell you what I did with that wonderful equestrian.'],
      ['K', 'happy', 'The boy is a king now. {w}We can’t have him topping off the wine glasses of bitter old spinsters at night.'],
      ['Q', '', 'I’m still his mother.'],
      ['K', '', 'But he’s not still your son. He’s his own man now.'],
      ['Q', '', 'Will you help me with the cocktail party?'],
      ['K', '', 'Just hire help for her, son.'],
      { choice: [
        { t: 'Help your mother serve drinks', d: 1, go: 'c2_help' },
        { t: 'Hire help for your mother', d: -1, go: 'c2_hire' },
      ] },
    ],
    c2_help: [
      ['Q', 'happy', 'Thx, love. Don’t forget to bring a serving apron. I’d hate for you to mess up your robes.'],
      ['K', 'smug', 'Just don’t forget to curtsy.'],
      { go: 'c2_od' },
    ],
    c2_hire: [
      ['K', 'happy', 'Great decision. You’re a king now. Can’t let your troops catch you moonlighting as a cocktail waitress.'],
      ['Q', 'snark', 'Someone’s too big to help their mother. {w}I’ll remember that.'],
      { go: 'c2_od' },
    ],
    // "OffenseOrDefense" and "BrisOrBallet" were written for the Dog side (DLevel3) but never wired in.
    c2_od: [
      ['Q', 'angry', 'As my father taught me, the key to winning the war is having the strongest defense.'],
      ['K', 'happy', 'But I taught you to believe that a strong enough sword will reduce any shield to a pile of splinters in the dirt.'],
      ['Q', '', 'Spoken like a man who lost a lot of wars.'],
      ['K', 'smug', 'Well, boring your enemies to death isn’t exactly winning either.'],
      ['Q', '', 'Is it a coincidence that you’re always here when I’m here, {w}or is my luck really that terrible?'],
      ['K', 'happy', 'Luck has nothing to do with it. I just like the way you smell. It reminds me of my childhood {w}when I was poor.'],
      ['K', '', 'Defense is most important if you don’t know how to fight.'],
      ['Q', '', 'Swords, and spears, and turrets, and bla bla bla. {w}How many times did my father have to rescue you from defeat?'],
      ['K', '', 'Things were going fine. I just wanted your dad to feel useful in his old age. {w}Now come on, boy. Tell your mother that offense is more important.'],
      ['Q', '', 'Tell your father that offense is for storytellers. Defense wins wars.'],
      { choice: [
        { t: 'Offense is more important', d: -1, go: 'c2_bris' },
        { t: 'Defense wins wars', d: 1, go: 'c2_bris' },
      ] },
    ],
    c2_bris: [
      ['B', '', 'Yo yo yo, clear your weekend. My son is getting the big cut at his bris ceremony.'],
      ['B', '', 'There’s gonna be imported beers and strippers at the after party. It’s gonna be SICK, YO!'],
      ['S', '', 'Sorry, brother, he has already committed to going to his niece’s first ballet recital.'],
      ['Y', '', '...'],
      ['S', '', 'You’re still going, right? {w}She’s been practicing for this recital for months.'],
      ['Q', 'angry', 'Go and see your niece dance. That’s the kind of family event an uncle is supposed to show up at.'],
      ['K', 'smug', 'Been there, done that. There’s gonna be another ballet performance pretty much every week. You’ll have plenty of other opportunities.'],
      ['Q', '', 'Your nephew is only eight days old. He’s not even gonna remember the cut, let alone whether or not you were there. He doesn’t even know who you are yet.'],
      ['K', 'happy', 'Well, {w}if you said you were going you should try and keep your word. But a young man’s bris ceremony is also an important event.'],
      ['Q', '', 'Dear ex-husband, I find it peculiar that you were at each of your son’s sporting events, but always had an important battle to fight when it came to your daughter’s ballet.'],
      ['K', '', 'Those are the responsibilities of being King.'],
      ['B', '', 'If you hurry, you can make the bris and MAYBE get to your niece’s ballet recital in time. Maybe. But it’s up to you if you wanna play it safe and choose one.'],
      ['S', '', 'I’d really like you to attend my daughter’s ballet performance. {w}Up to you, really.'],
      ['B', '', 'You can make both. Easy.'],
      { choice: [
        { t: 'Go to your niece’s ballet recital', d: 1, go: 'c2_ballet' },
        { t: 'Go to the bris, and MAYBE the ballet', d: -1, go: 'c2_brisGo' },
      ] },
    ],
    c2_ballet: [
      ['S', '', 'She’ll be SO happy to see you.'],
      ['B', '', 'Disappointing me, bro! :-('],
      { tally: 2 },
    ],
    c2_brisGo: [
      ['S', '', 'That’s okay. You don’t have to come.'],
      ['B', '', 'NOICE!!!'],
      { tally: 2 },
    ],
    t2_mom: [
      ['Q', 'angry', 'Come see me after the ballet recital. I have some new reinforcements for your defenses.'],
      ['K', 'angry', 'We’ll see if that helps. {w}I’m out.'],
      { finish: true },
    ],
    t2_dad: [
      ['K', 'happy', 'No son of mine is gonna lose a war. See me after and I’ve got new weapons for you.'],
      ['Q', 'angry', 'Whatever. {w}See if that helps.'],
      { finish: true },
    ],

    // ---------- Chapter 3 (CLevel5 / DLevel5) ----------
    c3_inherit: [
      ['Q', 'angry', 'So your father and I have been having a debate.'],
      ['Q', '', 'Don’t you think that when we die, we should split our fortunes equally between all three of our children?'],
      ['K', 'happy', 'She doesn’t know what she’s talking about. I love my daughter,'],
      ['K', '', 'but when a daughter marries, she has a new family to look after her.'],
      ['Q', '', 'My father didn’t stop looking after me just because I married you.'],
      ['K', '', 'I don’t know why he never trusted me.'],
      ['Q', '', 'Who would trust the loser of all wars to look after their daughter? {w}And you didn’t trust him either.'],
      ['K', '', 'I didn’t trust him because he was a vegetarian. I mean, {w}eww.'],
      ['K', '', 'Anyone who gets drunk and craves lettuce at 3 in the morning is a little questionable in my opinion.'],
      ['Q', '', 'What’s even more questionable is that you insisted on arguing with him about his veganism at every meal. {w}What kind of grown man fights about snacks?'],
      ['K', '', 'ALL SNACKS MATTER!'],
      ['K', '', 'But, but, back to the topic at hand. Shouldn’t we leave our inheritance to our future kings?'],
      ['Q', '', 'Don’t you think we should split it between all of our children evenly?'],
      { choice: [
        { t: 'Treat all the children equally', d: 1, go: 'c3_equal' },
        { t: 'The daughter is fine with her new family', d: -1, go: 'c3_noDaughter' },
      ] },
    ],
    c3_equal: [
      ['K', 'angry', 'What a waste.'],
      ['Q', 'angry', 'It’s the principle of the matter. How will your daughter know that you love her if you don’t show it?'],
      { go: 'c3_div' },
    ],
    c3_noDaughter: [
      ['K', 'happy', 'Exactly! {w}No reason to give her an army when she’s just going to give it to her husband. I already gave that man a dowry.'],
      ['Q', 'snark', 'I hope you’re not expecting your daughter to be the one that takes care of you in your old age.'],
      { go: 'c3_div' },
    ],
    c3_div: [
      ['Q', 'happy', 'Hello all. Wait, {w}I smell something. {w}More like I DON’T smell something. Where’s Trashley?'],
      ['Q', '', 'Did you send her back to get her G.E.D.?'],
      ['K', 'angry', 'It’s ASHLEY, and for the record, we’re no longer seeing each other.'],
      ['Q', '', 'Awww. Poor Smashley. She didn’t know you were the quitting type.'],
      ['K', '', 'Excuse me?'],
      ['Q', '', 'It’s obvious you don’t have the endurance for long-term commitments.'],
      ['K', '', 'I hope you’re not referring to our marriage.'],
      ['K', '', 'Son, will you please remind that sour birth canal of a mother {w}that it was in fact SHE who proposed that we get a divorce.'],
      ['Q', '', 'You weren’t supposed to really go through with it.'],
      ['K', 'smug', 'You weren’t supposed to sleep with the riding coach.'],
      ['Q', '', 'FAKE NEWS! Unconfirmed.'],
      ['Q', '', 'Son, will you please explain to your father that as much as he loved going to war, he should have fought to keep this family.'],
      ['K', '', 'Please tell that erratic booger-wolf that you call Mommy that I only fight battles I can win.'],
      ['K', '', 'No point in trying to make someone happy who doesn’t want to be.'],
      { choice: [
        { t: 'Dad, you should have never let her go', d: 1, go: 'c3_letGo' },
        { t: 'Mom, you shouldn’t have asked for a divorce if you didn’t mean it', d: -1, go: 'c3_shouldnt' },
      ] },
    ],
    c3_letGo: [
      ['Q', 'happy', 'You see. Even your own son knows you were just looking for a way out.'],
      { tally: 3 },
    ],
    c3_shouldnt: [
      ['K', 'happy', 'Even your son can see how erratic you are.'],
      ['Q', 'snark', 'I see whose side you’re going to take. {w}I’ll remember that.'],
      { tally: 3 },
    ],
    t3_mom: [
      ['Q', 'happy', 'At least you know your father is trash. I’ll make sure your defenses can win the war.'],
      ['K', 'angry', 'I hope you know what you’re doing. {w}You’ll get no help from me.'],
      { go: 'c3_end' },
    ],
    t3_dad: [
      ['K', 'happy', 'Most boys would automatically take the mother’s side in a divorce. You didn’t. {w}I respect that.'],
      ['K', '', 'Let’s pool our resources and win you that war.'],
      { go: 'c3_end' },
    ],
    c3_end: [
      ['K', 'smug', 'Why’d you start ignoring me after the kids were born?'],
      ['Q', 'snark', 'Is that what you think? {w}Oh no.'],
      { finish: true },
    ],
  },
};
